name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2024-09-27"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "d1"
database_name = "rhaeron"
database_id = "e35076f6-65ba-4939-a9d8-bf068af78f23"

[[kv_namespaces]]
binding = "kv"
id = "054685b645c14a79b3b7e3b6f2668591"

[[r2_buckets]]
binding = "r2"
bucket_name = "rhaeron"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
